INSERT INTO "spell" VALUES
    (NULL, "Absorb Elements", "Abjuration", 1, 0, 1),
	(NULL, "Alarm", "Abjuration", 1, 0, 1),
	(NULL, "Burning Hands", "Evocation", 1, 0, 1),
	(NULL, "Catapult", "Transmutation", 1, 0, 1),
	(NULL, "Cause Fear", "Necromancy", 1, 0, 1),
	(NULL, "Charm Person", "Enchantment", 1, 0, 1),
	(NULL, "Chromatic Orb", "Evocation", 1, 0, 1),
	(NULL, "Color Spray", "Illusion", 1, 0, 1),
	(NULL, "Comprehend Languages", "Divination", 1, 0, 1),
	(NULL, "Detect Magic", "Divination", 1, 0, 1),
	(NULL, "Disguise Self", "Illusion", 1, 0, 1),
	(NULL, "Distort Value", "Illusion", 1, 0, 1),
	(NULL, "Earth Tremor", "Evocation", 1, 0, 1),
	(NULL, "Expeditious Retreat", "Transmutation", 1, 0, 1),
	(NULL, "False Life", "Necromancy", 1, 0, 1),
	(NULL, "Feather Fall", "Transmutation", 1, 0, 1),
	(NULL, "Find Familiar", "Conjuration", 1, 0, 1),
	(NULL, "Fog Cloud", "Conjuration", 1, 0, 1),
	(NULL, "Frost Fingers", "Evocation", 1, 0, 1),
	(NULL, "Gift of Alacrity", "Divination", 1, 1, 0),
	(NULL, "Grease", "Conjuration", 1, 0, 1),
	(NULL, "Ice Knife", "Conjuration", 1, 0, 1),
	(NULL, "Identify", "Divination", 1, 0, 1),
	(NULL, "Illusory Script", "Illusion", 1, 0, 1),
	(NULL, "Jim's Magic Missile", "Evocation", 1, 0, 1),
	(NULL, "Jump", "Transmutation", 1, 0, 1),
	(NULL, "Longstrider", "Transmutation", 1, 0, 1),
	(NULL, "Mage Armor", "Abjuration", 1, 0, 1),
	(NULL, "Magic Missile", "Evocation", 1, 0, 1),
	(NULL, "Magnify Gravity", "Transmutation", 1, 1, 1),
	(NULL, "Protection from Evil and Good", "Abjuration", 1, 0, 1),
	(NULL, "Ray of Sickness", "Necromancy", 1, 0, 1),
	(NULL, "Shield", "Abjuration", 1, 0, 1),
	(NULL, "Silent Image", "Illusion", 1, 0, 1),
	(NULL, "Silvery Barbs", "Enchantment", 1, 0, 0),
	(NULL, "Sleep", "Enchantment", 1, 0, 1),
	(NULL, "Snare", "Abjuration", 1, 0, 1),
	(NULL, "Tasha's Caustic Brew", "Evocation", 1, 0, 1),
	(NULL, "Tasha's Hideous Laughter", "Enchantment", 1, 0, 1),
	(NULL, "Tenser's Floating Disk", "Conjuration", 1, 0, 1),
	(NULL, "Thunderwave", "Evocation", 1, 0, 1),
	(NULL, "Unseen Servant", "Conjuration", 1, 0, 1),
	(NULL, "Witch Bolt", "Evocation", 1, 0, 1);

INSERT INTO "spell" VALUES
	(NULL, "Aganazzar's Scorcher", "Evocation", 2, 0, 1),
	(NULL, "Alter Self", "Transmutation", 2, 0, 1),
	(NULL, "Arcane Lock", "Abjuration", 2, 0, 1),
	(NULL, "Augury", "Divination", 2, 0, 1),
	(NULL, "Blindness/Deafness", "Necromancy", 2, 0, 1),
	(NULL, "Blur", "Illusion", 2, 0, 1),
	(NULL, "Borrowed Knowledge", "Divination", 2, 0, 1),
	(NULL, "Cloud of Daggers", "Conjuration", 2, 0, 1),
	(NULL, "Continual Flame", "Evocation", 2, 0, 1),
	(NULL, "Crown of Madness", "Enchantment", 2, 0, 1),
	(NULL, "Darkness", "Evocation", 2, 0, 1),
	(NULL, "Darkvision", "Transmutation", 2, 0, 1),
	(NULL, "Detect Thoughts", "Divination", 2, 0, 1),
	(NULL, "Dragon's Breath", "Transmutation", 2, 0, 1),
	(NULL, "Dust Devil", "Conjuration", 2, 0, 1),
	(NULL, "Earthbind", "Transmutation", 2, 0, 1),
	(NULL, "Enhance Ability", "Transmutation", 2, 0, 1),
	(NULL, "Enlarge/Reduce", "Transmutation", 2, 0, 1),
	(NULL, "Flaming Sphere", "Conjuration", 2, 0, 1),
	(NULL, "Flock of Familiars", "Conjuration", 2, 0, 0),
	(NULL, "Fortune's Favor", "Divination", 2, 1, 1),
	(NULL, "Gentle Repose", "Necromancy", 2, 0, 1),
	(NULL, "Gift of Gab", "Enchantment", 2, 0, 1),
	(NULL, "Gust of Wind", "Evocation", 2, 0, 1),
	(NULL, "Hold Person", "Enchantment", 2, 0, 1),
	(NULL, "Immovable Object", "Transmutation", 2, 1, 1),
	(NULL, "Invisibility", "Illusion", 2, 0, 1),
	(NULL, "Jim's Glowing Coin", "Enchantment", 2, 0, 1),
	(NULL, "Kinetic Jaunt", "Transmutation", 2, 0, 1),
	(NULL, "Knock", "Transmutation", 2, 0, 1),
	(NULL, "Levitate", "Transmutation", 2, 0, 1),
	(NULL, "Locate Object", "Divination", 2, 0, 1),
	(NULL, "Magic Mouth", "Illusion", 2, 0, 1),
	(NULL, "Magic Weapon", "Transmutation", 2, 0, 1),
	(NULL, "Maximilian's Earthen Grasp", "Transmutation", 2, 0, 1),
	(NULL, "Melf's Acid Arrow", "Evocation", 2, 0, 1),
	(NULL, "Mind Spike", "Divination", 2, 0, 1),
	(NULL, "Mirror Image", "Illusion", 2, 0, 1),
	(NULL, "Misty Step", "Conjuration", 2, 0, 1),
	(NULL, "Nathair's Mischief", "Illusion", 2, 0, 1),
	(NULL, "Nystul's Magic Aura", "Illusion", 2, 0, 1),
	(NULL, "Phantasmal Force", "Illusion", 2, 0, 1),
	(NULL, "Pyrotechnics", "Transmutation", 2, 0, 1),
	(NULL, "Ray of Enfeeblement", "Necromancy", 2, 0, 1),
	(NULL, "Rime's Binding Ice", "Evocation", 2, 0, 1),
	(NULL, "Rope Trick", "Transmutation", 2, 0, 1),
	(NULL, "Scorching Ray", "Evocation", 2, 0, 1),
	(NULL, "See Invisibility", "Divination", 2, 0, 1),
	(NULL, "Shadow Blade", "Illusion", 2, 0, 1),
	(NULL, "Shatter", "Evocation", 2, 0, 1),
	(NULL, "Skywrite", "Transmutation", 2, 0, 1),
	(NULL, "Snilloc's Snowball Swarm", "Evocation", 2, 0, 1),
	(NULL, "Spider Climb", "Transmutation", 2, 0, 1),
	(NULL, "Suggestion", "Enchantment", 2, 0, 1),
	(NULL, "Tasha's Mind Whip", "Enchantment", 2, 0, 1),
	(NULL, "Vortex Warp", "Conjuration", 2, 0, 1),
	(NULL, "Warding Wind", "Evocation", 2, 0, 1),
	(NULL, "Web", "Conjuration", 2, 0, 1),
	(NULL, "Wither and Bloom", "Necromancy", 2, 0, 1),
	(NULL, "Wristpocket", "Conjuration", 2, 1, 1);
	
INSERT INTO "spell" VALUES
	(NULL, "Animate Dead", "Necromancy", 3, 0, 1),
	(NULL, "Ashardalon's Stride", "Transmutation", 3, 0, 1),
	(NULL, "Bestow Curse", "Necromancy", 3, 0, 1),
	(NULL, "Blink", "Transmutation", 3, 0, 1),
	(NULL, "Catnap", "Enchantment", 3, 0, 1),
	(NULL, "Clairvoyance", "Divination", 3, 0, 1),
	(NULL, "Counterspell", "Abjuration", 3, 0, 1),
	(NULL, "Dispel Magic", "Abjuration", 3, 0, 1),
	(NULL, "Enemies Abound", "Enchantment", 3, 0, 1),
	(NULL, "Erupting Earth", "Transmutation", 3, 0, 1),
	(NULL, "Fast Friends", "Enchantment", 3, 0, 1),
	(NULL, "Fear", "Illusion", 3, 0, 1),
	(NULL, "Feign Death", "Necromancy", 3, 0, 1),
	(NULL, "Fireball", "Evocation", 3, 0, 1),
	(NULL, "Flame Arrows", "Transmutation", 3, 0, 1),
	(NULL, "Fly", "Transmutation", 3, 0, 1),
	(NULL, "Galder's Tower", "Conjuration", 3, 0, 0),
	(NULL, "Gaseous Form", "Transmutation", 3, 0, 1),
	(NULL, "Glyph of Warding", "Abjuration", 3, 0, 1),
	(NULL, "Haste", "Transmutation", 3, 0, 1),
	(NULL, "Hypnotic Pattern", "Illusion", 3, 0, 1),
	(NULL, "Incite Greed", "Enchantment", 3, 0, 1),
	(NULL, "Intellect Fortress", "Abjuration", 3, 0, 1),
	(NULL, "Leomund's Tiny Hut", "Evocation", 3, 0, 1),
	(NULL, "Life Transference", "Necromancy", 3, 0, 1),
	(NULL, "Lightning Bolt", "Evocation", 3, 0, 1),
	(NULL, "Magic Circle", "Abjuration", 3, 0, 1),
	(NULL, "Major Image", "Illusion", 3, 0, 1),
	(NULL, "Melf's Minute Meteors", "Evocation", 3, 0, 1),
	(NULL, "Nondetection", "Abjuration", 3, 0, 1),
	(NULL, "Phantom Steed", "Illusion", 3, 0, 1),
	(NULL, "Protection from Energy", "Abjuration", 3, 0, 1),
	(NULL, "Pulse Wave", "Evocation", 3, 1, 1),
	(NULL, "Remove Curse", "Abjuration", 3, 0, 1),
	(NULL, "Sending", "Evocation", 3, 0, 1),
	(NULL, "Sleet Storm", "Conjuration", 3, 0, 1),
	(NULL, "Slow", "Transmutation", 3, 0, 1),
	(NULL, "Speak with Dead", "Necromancy", 3, 0, 1),
	(NULL, "Spirit Shroud", "Necromancy", 3, 0, 1),
	(NULL, "Stinking Cloud", "Conjuration", 3, 0, 1),
	(NULL, "Summon Fey", "Conjuration", 3, 0, 1),
	(NULL, "Summon Lesser Demons", "Conjuration", 3, 0, 1),
	(NULL, "Summon Shadowspawn", "Conjuration", 3, 0, 1),
	(NULL, "Summon Undead", "Necromancy", 3, 0, 1),
	(NULL, "Thunder Step", "Conjuration", 3, 0, 1),
	(NULL, "Tidal Wave", "Conjuration", 3, 0, 1),
	(NULL, "Tiny Servant", "Transmutation", 3, 0, 1),
	(NULL, "Tongues", "Divination", 3, 0, 1),
	(NULL, "Vampiric Touch", "Necromancy", 3, 0, 1),
	(NULL, "Wall of Sand", "Evocation", 3, 0, 1),
	(NULL, "Wall of Water", "Evocation", 3, 0, 1),
	(NULL, "Water Breathing", "Transmutation", 3, 0, 1);

INSERT INTO "spell" VALUES
	(NULL, "Arcane Eye", "Divination", 4, 0, 1),
	(NULL, "Banishment", "Abjuration", 4, 0, 1),
	(NULL, "Blight", "Necromancy", 4, 0, 1),
	(NULL, "Charm Monster", "Enchantment", 4, 0, 1),
	(NULL, "Confusion", "Enchantment", 4, 0, 1),
	(NULL, "Conjure Minor Elementals", "Conjuration", 4, 0, 1),
	(NULL, "Control Water", "Transmutation", 4, 0, 1),
	(NULL, "Dimension Door", "Conjuration", 4, 0, 1),
	(NULL, "Divination", "Divination", 4, 0, 1),
	(NULL, "Elemental Bane", "Transmutation", 4, 0, 1),
	(NULL, "Evard's Black Tentacles", "Conjuration", 4, 0, 1),
	(NULL, "Fabricate", "Transmutation", 4, 0, 1),
	(NULL, "Fire Shield", "Evocation", 4, 0, 1),
	(NULL, "Galder's Speedy Courier", "Conjuration", 4, 0, 0),
	(NULL, "Gravity Sinkhole", "Evocation", 4, 1, 1),
	(NULL, "Greater Invisibility", "Illusion", 4, 0, 1),
	(NULL, "Hallucinatory Terrain", "Illusion", 4, 0, 1),
	(NULL, "Ice Storm", "Evocation", 4, 0, 1),
	(NULL, "Leomund's Secret Chest", "Conjuration", 4, 0, 1),
	(NULL, "Locate Creature", "Divination", 4, 0, 1),
	(NULL, "Mordenkainen's Faithful Hound", "Conjuration", 4, 0, 1),
	(NULL, "Mordenkainen's Private Sanctum", "Abjuration", 4, 0, 1),
	(NULL, "Otiluke's Resilient Sphere", "Evocation", 4, 0, 1),
	(NULL, "Phantasmal Killer", "Illusion", 4, 0, 1),
	(NULL, "Polymorph", "Transmutation", 4, 0, 1),
	(NULL, "Raulothim's Psychic Lance", "Enchantment", 4, 0, 1),
	(NULL, "Sickening Radiance", "Evocation", 4, 0, 1),
	(NULL, "Stone Shape", "Transmutation", 4, 0, 1),
	(NULL, "Stoneskin", "Abjuration", 4, 0, 1),
	(NULL, "Storm Sphere", "Evocation", 4, 0, 1),
	(NULL, "Summon Aberration", "Conjuration", 4, 0, 1),
	(NULL, "Summon Construct", "Conjuration", 4, 0, 1),
	(NULL, "Summon Elemental", "Conjuration", 4, 0, 1),
	(NULL, "Summon Greater Demon", "Conjuration", 4, 0, 1),
	(NULL, "Vitriolic Sphere", "Evocation", 4, 0, 1),
	(NULL, "Wall of Fire", "Evocation", 4, 0, 1),
	(NULL, "Watery Sphere", "Conjuration", 4, 0, 1);

INSERT INTO "spell" VALUES
	(NULL, "Animate Objects", "Transmutation", 5, 0, 1),
	(NULL, "Bigby's Hand", "Evocation", 5, 0, 1),
	(NULL, "Cloudkill", "Conjuration", 5, 0, 1),
	(NULL, "Cone of Cold", "Evocation", 5, 0, 1),
	(NULL, "Conjure Elemental", "Conjuration", 5, 0, 1),
	(NULL, "Contact Other Plane", "Divination", 5, 0, 1),
	(NULL, "Control Winds", "Transmutation", 5, 0, 1),
	(NULL, "Creation", "Illusion", 5, 0, 1),
	(NULL, "Danse Macabre", "Necromancy", 5, 0, 1),
	(NULL, "Dawn", "Evocation", 5, 0, 1),
	(NULL, "Dominate Person", "Enchantment", 5, 0, 1),
	(NULL, "Dream", "Illusion", 5, 0, 1),
	(NULL, "Enervation", "Necromancy", 5, 0, 1),
	(NULL, "Far Step", "Conjuration", 5, 0, 1),
	(NULL, "Geas", "Enchantment", 5, 0, 1),
	(NULL, "Hold Monster", "Enchantment", 5, 0, 1),
	(NULL, "Immolation", "Evocation", 5, 0, 1),
	(NULL, "Infernal Calling", "Conjuration", 5, 0, 1),
	(NULL, "Legend Lore", "Divination", 5, 0, 1),
	(NULL, "Mislead", "Illusion", 5, 0, 1),
	(NULL, "Modify Memory", "Enchantment", 5, 0, 1),
	(NULL, "Negative Energy Flood", "Necromancy", 5, 0, 1),
	(NULL, "Passwall", "Transmutation", 5, 0, 1),
	(NULL, "Planar Binding", "Abjuration", 5, 0, 1),
	(NULL, "Rary's Telepathic Bond", "Divination", 5, 0, 1),
	(NULL, "Scrying", "Divination", 5, 0, 1),
	(NULL, "Seeming", "Illusion", 5, 0, 1),
	(NULL, "Skill Empowerment", "Transmutation", 5, 0, 1),
	(NULL, "Steel Wind Strike", "Conjuration", 5, 0, 1),
	(NULL, "Summon Draconic Spirit", "Conjuration", 5, 0, 1),
	(NULL, "Synaptic Static", "Enchantment", 5, 0, 1),
	(NULL, "Telekinesis", "Transmutation", 5, 0, 1),
	(NULL, "Teleportation Circle", "Conjuration", 5, 0, 1),
	(NULL, "Temporal Shunt", "Transmutation", 5, 1, 0),
	(NULL, "Transmute Rock", "Transmutation", 5, 0, 1),
	(NULL, "Wall of Force", "Evocation", 5, 0, 1),
	(NULL, "Wall of Light", "Evocation", 5, 0, 1),
	(NULL, "Wall of Stone", "Evocation", 5, 0, 1);

INSERT INTO "spell" VALUES
	(NULL, "Arcane Gate", "Conjuration", 6, 0, 1),
	(NULL, "Chain Lightning", "Evocation", 6, 0, 1),
	(NULL, "Circle of Death", "Necromancy", 6, 0, 1),
	(NULL, "Contingency", "Evocation", 6, 0, 1),
	(NULL, "Create Homunculus", "Transmutation", 6, 0, 1),
	(NULL, "Create Undead", "Necromancy", 6, 0, 1),
	(NULL, "Disintegrate", "Transmutation", 6, 0, 1),
	(NULL, "Drawmij's Instant Summons", "Conjuration", 6, 0, 1),
	(NULL, "Eyebite", "Necromancy", 6, 0, 1),
	(NULL, "Fizban's Platinum Shield", "Abjuration", 6, 0, 1),
	(NULL, "Flesh to Stone", "Transmutation", 6, 0, 1),
	(NULL, "Globe of Invulnerability", "Abjuration", 6, 0, 1),
	(NULL, "Gravity Fissure", "Evocation", 6, 1, 1),
	(NULL, "Guards and Wards", "Abjuration", 6, 0, 1),
	(NULL, "Investiture of Flame", "Transmutation", 6, 0, 1),
	(NULL, "Investiture of Ice", "Transmutation", 6, 0, 1),
	(NULL, "Investiture of Stone", "Transmutation", 6, 0, 1),
	(NULL, "Investiture of Wind", "Transmutation", 6, 0, 1),
	(NULL, "Magic Jar", "Necromancy", 6, 0, 1),
	(NULL, "Mass Suggestion", "Enchantment", 6, 0, 1),
	(NULL, "Mental Prison", "Illusion", 6, 0, 1),
	(NULL, "Move Earth", "Transmutation", 6, 0, 1),
	(NULL, "Otiluke's Freezing Sphere", "Evocation", 6, 0, 1),
	(NULL, "Otto's Irresistible Dance", "Enchantment", 6, 0, 1),
	(NULL, "Programmed Illusion", "Illusion", 6, 0, 1),
	(NULL, "Scatter", "Conjuration", 6, 0, 1),
	(NULL, "Soul Cage", "Necromancy", 6, 0, 1),
	(NULL, "Summon Fiend", "Conjuration", 6, 0, 1),
	(NULL, "Sunbeam", "Evocation", 6, 0, 1),
	(NULL, "Tasha's Otherworldly Guise", "Transmutation", 6, 0, 1),
	(NULL, "Tenser's Transformation", "Transmutation", 6, 0, 1),
	(NULL, "True Seeing", "Divination", 6, 0, 1),
	(NULL, "Wall of Ice", "Evocation", 6, 0, 1);

INSERT INTO "spell" VALUES
	(NULL, "Create Magen", "Transmutation", 7, 0, 1),
	(NULL, "Crown of Stars", "Evocation", 7, 0, 1),
	(NULL, "Delayed Blast Fireball", "Evocation", 7, 0, 1),
	(NULL, "Draconic Transformation", "Transmutation", 7, 0, 1),
	(NULL, "Dream of the Blue Veil", "Conjuration", 7, 0, 0),
	(NULL, "Etherealness", "Transmutation", 7, 0, 1),
	(NULL, "Finger of Death", "Necromancy", 7, 0, 1),	
	(NULL, "Forcecage", "Evocation", 7, 0, 1),
	(NULL, "Mirage Arcane", "Illusion", 7, 0, 1),
	(NULL, "Mordenkainen's Magnificent Mansion", "Conjuration", 7, 0, 1),
	(NULL, "Mordenkainen's Sword", "Evocation", 7, 0, 1),
	(NULL, "Plane Shift", "Conjuration", 7, 0, 1),
	(NULL, "Power Word Pain", "Enchantment", 7, 0, 1),
	(NULL, "Prismatic Spray", "Evocation", 7, 0, 1),
	(NULL, "Project Image", "Illusion", 7, 0, 1),
	(NULL, "Reverse Gravity", "Transmutation", 7, 0, 1),
	(NULL, "Sequester", "Transmutation", 7, 0, 1),
	(NULL, "Simulacrum", "Illusion", 7, 0, 1),
	(NULL, "Symbol", "Abjuration", 7, 0, 1),
	(NULL, "Teleport", "Conjuration", 7, 0, 1),
	(NULL, "Tether Essence", "Necromancy", 7, 1, 1),
	(NULL, "Whirlwind", "Evocation", 7, 0, 1);

INSERT INTO "spell" VALUES
	(NULL, "Abi-Dalzim's Horrid Wilting", "Necromancy", 8, 0, 1),
	(NULL, "Antimagic Field", "Abjuration", 8, 0, 1),
	(NULL, "Antipathy/Sympathy", "Enchantment", 8, 0, 1),
	(NULL, "Clone", "Necromancy", 8, 0, 1),
	(NULL, "Control Weather", "Transmutation", 8, 0, 1),
	(NULL, "Dark Star", "Evocation", 8, 1, 1),
	(NULL, "Demiplane", "Conjuration", 8, 0, 1),
	(NULL, "Dominate Monster", "Enchantment", 8, 0, 1),
	(NULL, "Feeblemind", "Enchantment", 8, 0, 1),
	(NULL, "Illusory Dragon", "Illusion", 8, 0, 1),
	(NULL, "Incendiary Cloud", "Conjuration", 8, 0, 1),
	(NULL, "Maddening Darkness", "Evocation", 8, 0, 1),
	(NULL, "Maze", "Conjuration", 8, 0, 1),
	(NULL, "Mighty Fortress", "Conjuration", 8, 0, 1),
	(NULL, "Mind Blank", "Abjuration", 8, 0, 1),
	(NULL, "Power Word Stun", "Enchantment", 8, 0, 1),
	(NULL, "Reality Break", "Conjuration", 8, 1, 0),
	(NULL, "Sunburst", "Evocation", 8, 0, 1),
	(NULL, "Telepathy", "Evocation", 8, 0, 1);
	
INSERT INTO "spell" VALUES
	(NULL, "Astral Projection", "Necromancy", 9, 0, 1),
	(NULL, "Blade of Disaster", "Conjuration", 9, 0, 1),
	(NULL, "Foresight", "Divination", 9, 0, 1),
	(NULL, "Gate", "Conjuration", 9, 0, 1),
	(NULL, "Imprisonment", "Abjuration", 9, 0, 1),
	(NULL, "Invulnerability", "Abjuration", 9, 0, 1),
	(NULL, "Mass Polymorph", "Transmutation", 9, 0, 1),
	(NULL, "Meteor Swarm", "Evocation", 9, 0, 1),
	(NULL, "Power Word Kill", "Enchantment", 9, 0, 1),
	(NULL, "Prismatic Wall", "Abjuration", 9, 0, 1),
	(NULL, "Psychic Scream", "Enchantment", 9, 0, 1),
	(NULL, "Ravenous Void", "Evocation", 9, 1, 1),
	(NULL, "Shapechange", "Transmutation", 9, 0, 1),
	(NULL, "Time Ravage", "Necromancy", 9, 1, 0),
	(NULL, "Time Stop", "Transmutation", 9, 0, 1),
	(NULL, "True Polymorph", "Transmutation", 9, 0, 1),
	(NULL, "Weird", "Illusion", 9, 0, 1),
	(NULL, "Wish", "Conjuration", 9, 0, 1);